# Generated by Django 4.0 on 2022-01-03 20:57

from django.db import migrations, models
import user_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='image',
            field=models.ImageField(default=1, upload_to=user_app.models.Department.get_file_name),
            preserve_default=False,
        ),
    ]
