# Generated by Django 4.0 on 2022-01-03 21:39

from django.db import migrations, models
import django.db.models.deletion
import user_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_department_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('image', models.ImageField(upload_to=user_app.models.Doctor.get_file_name)),
                ('post', models.CharField(max_length=100)),
                ('room', models.CharField(max_length=50)),
                ('schedule', models.TextField(blank=True)),
                ('is_manager', models.BooleanField(default=False)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.department')),
            ],
            options={
                'ordering': ('department',),
            },
        ),
    ]
