# Generated by Django 4.0 on 2024-10-25 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_delete_document_blog_file_alter_blog_category_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.AddField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(help_text="Введіть номер телефону в форматі: '+38(0XX) XXX XX-XX'.", max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='images/blogs/no-image-doc.png', null=True, upload_to='images/blogs'),
        ),
    ]
