# Generated by Django 4.0 on 2022-01-04 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='is_director',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doctor',
            name='is_extdirector',
            field=models.BooleanField(default=False),
        ),
    ]
