# Generated by Django 4.0 on 2022-01-05 16:54

from django.db import migrations, models
import django.db.models.deletion
import user_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_doctor_is_director_doctor_is_extdirector'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('image', models.ImageField(upload_to=user_app.models.Administration.get_file_name)),
                ('post', models.CharField(max_length=50)),
                ('room', models.CharField(max_length=50)),
                ('schedule', models.TextField(blank=True)),
                ('phone', models.CharField(max_length=25)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.department')),
            ],
            options={
                'ordering': ('department', 'post'),
            },
        ),
    ]
