# Generated by Django 4.0 on 2022-01-05 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_administration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administration',
            name='room',
        ),
    ]
