# Generated by Django 4.0 on 2022-01-05 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0006_remove_administration_room'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administration',
            options={'ordering': ('post',)},
        ),
        migrations.RemoveField(
            model_name='administration',
            name='department',
        ),
    ]
