# Generated by Django 4.0 on 2022-01-05 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0011_alter_doctor_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ('-create',)},
        ),
    ]
