# Generated by Django 4.0 on 2022-01-05 21:00

from django.db import migrations, models
import django.db.models.deletion
import user_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0012_alter_blog_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=user_app.models.BlogImage.get_file_name)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.blog')),
            ],
            options={
                'ordering': ('-blog',),
            },
        ),
    ]
