# Generated by Django 4.0 on 2022-01-05 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0014_blog_slug_alter_blog_title'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='blog',
            index_together={('id', 'slug')},
        ),
    ]
