# Generated by Django 4.0 on 2022-01-05 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0016_alter_blog_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='create',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
