# Generated by Django 4.0 on 2022-01-06 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0017_alter_blog_create'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administration',
            options={'ordering': ('position',)},
        ),
        migrations.AddField(
            model_name='administration',
            name='position',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
