# Generated by Django 4.0 on 2022-01-10 13:35

from django.db import migrations, models
import user_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0019_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to=user_app.models.Document.get_file_name)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
